name: ml_project
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - matplotlib
      - numpy
      - pandas
      - seaborn
      - scikit-learn
      - pgmpy
      - torch
      - statsmodels
      - tqdm
      - ipykernel
      - jupyter
  - pygraphviz
